### ISSUE TITLE
UAC confirmation and command prompt window

### ISSUE THREAD

**Issue by Polygon1177** [SystemXFiles/process-governor#1] opened 2023-11-06 15:28 UTC
Hi there, great tool - I'm using it for Steelseries Sonar. : )

Is there a way to avoid having to confirm the UAC popup, and the command prompt showing up?

Thanks!

**Comment by SystemXFiles** [comment] 2023-11-06 17:50
@Polygon1177 Hi!

I'm glad to see you're using Process Governor. To assist you further, I need to clarify a couple of things:

1. Have you downloaded the latest version of the program?
2. Are you launching it using the `Process Governor.exe` file or the `process-governor.py` script?

I would also like to remind you that it's crucial to run the program with administrative rights for it to function correctly, as some features may not work as expected without them.

**Comment by Polygon1177** [comment] 2023-11-06 18:27
Hi there, thanks for your quick reply.

> 1. Have you downloaded the latest version of the program?

Yes, just started to use it yesterday, having downloaded the latest version.

> 2. Are you launching it using the `Process Governor.exe` file or the `process-governor.py` script?

I'm using the binary file.

> I would also like to remind you that it's crucial to run the program with administrative rights for it to function correctly, as some features may not work as expected without them.

I do understand it needs admin rights for its functionality to work properly.

I right-clicked the systray icon and checked "Run on Startup". All works well, but I was just wondering if there's a way to get around the admin confirmation pop-up, and if the command prompt window can somehow be hidden. : )

Also, I'm on WIndows 11 Home 23H2 22631.2506.

Thanks!

**Comment by SystemXFiles** [comment] 2023-11-06 19:48
Thank you for the clarification. 

Are you referring to the command prompt window that briefly appears before the Process Governor starts upon Windows startup? If so, this is standard behavior due to Windows restrictions that prevent executable files from being run with administrative rights at startup directly. As a result, a workaround through a script was implemented, which launches Process Governor with the necessary rights.

I will try to find an alternative solution to avoid the command prompt window's appearance, and possibly a way to eliminate the UAC prompt altogether at startup with Windows. 

I will update you in the comments here if I find a solution.

**Comment by SystemXFiles** [comment] 2023-11-13 06:04
Hello, @Polygon1177 !

I'm pleased to inform you that the issue you reported regarding UAC prompts and console window appearance during autostart has been resolved in our latest release.

Task Scheduler integration has been implemented for managing the autostart process, effectively eliminating UAC prompts and console window appearances at startup. This change ensures a smoother and more user-friendly experience.

**Comment by SystemXFiles** [comment] 2023-11-14 15:04
@Polygon1177
I found out what the problem was and fixed it in version [1.1.5](https://github.com/SystemXFiles/process-governor/releases/tag/v1.1.5)

Can you please test the new version of the application and let me know if the problem is fixed now?

**Closed** 2023-11-16 10:17 UTC
Labels: bug, enhancement
