### ISSUE TITLE
FileNotFoundError, QueryServiceConfigW

### ISSUE THREAD

**Issue by Edward-Lucas** [SystemXFiles/process-governor#17] opened 2024-03-06 13:53 UTC
`2024-03-06` 22:45:11,647 - proc-gov - ERROR - Error in the loop of loading and applying rules.
Traceback (most recent call last):
  File "main_loop.py", line 57, in main_loop
  File "service\rules_service.py", line 50, in apply_rules
  File "service\services_info_service.py", line 35, in get_list
  File "psutil\_pswindows.py", line 611, in as_dict
  File "psutil\_pswindows.py", line 522, in _query_config
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다: '(originated from `QueryServiceConfigW)'`

'지정된 파일을 찾을 수 없습니다.' is 'The system cannot find the file specified'

I'm experiencing audio problems in windows. Always have to change priorities in task manager.
Your program will be of great help to me. However, the program does not work with an error message.

![image](https://github.com/SystemXFiles/process-governor/assets/80303358/6c5811e1-7924-4b7f-ba5d-039b26ec3ca2)

**Comment by SystemXFiles** [comment] 2024-03-06 14:07
@Edward-Lucas Hello!

Do you have services on your PC that have names that include the characters: 지정된 파일을 찾을 수 없습니다 ?

Because it is very likely that when receiving a list of services, an unexpected name was received and this led to a crash. If this is so, then the bug may be incurable, because this is a problem with the third-party psutil library, which is used to obtain a list of services.

**Comment by Edward-Lucas** [comment] 2024-03-06 15:51
'지정된 파일을 찾을 수 없습니다' is Korean. Since I am using Korean, the error message is displayed in Korean.

The meaning is ‘The system cannot find the file specified’.

My knowledge is small. I don't know what the psutil library is.
I downloaded Python by searching on Google and used the command ‘-python -m pip install psutil’. The situation is the same. Is there anything else I can try?

**Comment by SystemXFiles** [comment] 2024-03-06 16:08
I found an opportunity to “fix” the problem, I will try to do it in the near future. But in fact, this will be ignoring the problematic service. I don’t see any other way to quickly fix the problem in the dependent library. In theory, the authors of psutil should fix this, maybe I’ll find the time to open an Issue with them.

**Comment by Edward-Lucas** [comment] 2024-03-06 17:12
wow, thank you

**Comment by SystemXFiles** [comment] 2024-03-07 13:47
@Edward-Lucas I've made some fixes to the app and can you please check if the issue is actually fixed?
Fixed in release https://github.com/SystemXFiles/process-governor/releases/tag/v1.2.1

**Comment by Edward-Lucas** [comment] 2024-03-07 15:54
Error has been changed.

2024-03-08 00:15:47,845 - proc-gov - INFO - Application started
2024-03-08 00:17:16,507 - proc-gov - ERROR - Error in the loop of loading and applying rules.
Traceback (most recent call last):
  File "main_loop.py", line 57, in main_loop
  File "service\rules_service.py", line 50, in apply_rules
  File "service\services_info_service.py", line 44, in get_list
  File "psutil\_pswindows.py", line 611, in as_dict
  File "util\decorators.py", line 122, in wrapper
  File "psutil\_pswindows.py", line 522, in _query_config
OSError: [WinError 15100] The resource loader failed to find the MUI file: '(originated from QueryServiceConfigW)'

My main computer is Windows 11 Pro N. I thought Windows might be the problem, so I tried it with a Windows 11 Home laptop, but got the same error.

**Comment by SystemXFiles** [comment] 2024-03-07 16:12
Made some more changes to catch a wider range of errors, can you please re-download the application (I updated the archive)?

**Comment by Edward-Lucas** [comment] 2024-03-11 17:21
I used it for a few days. Everything works perfectly.
No errors, it actually changes the settings of services and applications.
Thanks to this, you can now use the microphone normally.

**Comment by SystemXFiles** [comment] 2024-03-12 05:09
I'm glad that the application is stable and helps you =) Thanks for the feedback!

I close the task

**Closed by SystemXFiles** 2024-03-12 05:09 UTC
Labels: bug, P:High
